/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommonRouteImport } from './routes/common'

const PokemonLazyRouteImport = createFileRoute('/pokemon')()
const AnonLazyRouteImport = createFileRoute('/anon')()
const IndexLazyRouteImport = createFileRoute('/')()

const PokemonLazyRoute = PokemonLazyRouteImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pokemon.lazy').then((d) => d.Route))
const AnonLazyRoute = AnonLazyRouteImport.update({
  id: '/anon',
  path: '/anon',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/anon.lazy').then((d) => d.Route))
const CommonRoute = CommonRouteImport.update({
  id: '/common',
  path: '/common',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/common': typeof CommonRoute
  '/anon': typeof AnonLazyRoute
  '/pokemon': typeof PokemonLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/common': typeof CommonRoute
  '/anon': typeof AnonLazyRoute
  '/pokemon': typeof PokemonLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/common': typeof CommonRoute
  '/anon': typeof AnonLazyRoute
  '/pokemon': typeof PokemonLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/common' | '/anon' | '/pokemon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/common' | '/anon' | '/pokemon'
  id: '__root__' | '/' | '/common' | '/anon' | '/pokemon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CommonRoute: typeof CommonRoute
  AnonLazyRoute: typeof AnonLazyRoute
  PokemonLazyRoute: typeof PokemonLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemon': {
      id: '/pokemon'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anon': {
      id: '/anon'
      path: '/anon'
      fullPath: '/anon'
      preLoaderRoute: typeof AnonLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common': {
      id: '/common'
      path: '/common'
      fullPath: '/common'
      preLoaderRoute: typeof CommonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CommonRoute: CommonRoute,
  AnonLazyRoute: AnonLazyRoute,
  PokemonLazyRoute: PokemonLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
